resources:
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: "0 */12 * * *"   # e.g. UTC time zone, trigger at minute 0 past every 12th hour.


pipelines:
  - name: pipeline_scheduled_triggers
    steps:
      - name: step_1_scheduled_triggers
        type: Bash
        configuration:
          inputResources:
            - name: cron_trigger
        execution:
          onExecute:
            - printenv
